svg/Models/Tree.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace svg.Models
{
    public class Tree
    {
        public Guid Id { get; set; }

        [StringLength(50)]
        public string Name { get; set; }
        
        public virtual ICollection<TreeElement> Children { get; set; }
    }
}

svg/ViewModels/TreeThumbnailView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace svgProject.ViewModels
{
    public class TreeThumbnailView
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public Guid ThumbnailId { get; set; }
    }
}

svg/ViewModels/TreeView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace svgProject.ViewModels
{
    public class TreeView
    {
        public string Name { get; set; }
        public Guid MainObjectId { get; set; }
    }
}

svg/Controllers/TreesController.cs
using svg.Models;
using svg.ViewModels;
using Svg;
using svgProject.AjaxModels;
using svgProject.ViewModels;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using System.Xml;

namespace svg.Controllers
{
    public class TreesController : Controller
    {
        private SvgManager _manager = new SvgManager();
        private JavaScriptSerializer serializer = new JavaScriptSerializer();

        public ActionResult Index(string q)
        {
            var trees = _manager.GetTrees(q);
            var model = new TreesListView()
            {
                Trees = trees.Select(t => new TreeThumbnailView()
                {
                    Id = t.Id,
                    Name = t.Name,
                }),
                Keyword = q
            };
            return View(model);
        }

        [Authorize(Roles = "Administrator, User")]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, User")]
        public ActionResult Add(TreeView model)
        {


            if (ModelState.IsValid)
            {
                var newTree = new Tree()
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name
                };
                _manager.AddTree(newTree);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Review(Guid id)
        {
            var parent = _manager.GetParentElement(id);

            return View(new ReviewTreeView()
            {
                TreeId = parent.TreeId,
                ImageText = parent.Value,
                Name = parent.Tree.Name,
                ParentId = parent.Id
            });
        }

        //need for method GetThumbnailImage
        private bool ThumbnailCallBack()
        {
            return false;
        }

        [Authorize(Roles = "Administrator, User")]
        public ActionResult Edit(Guid id)
        {
            var tree = _manager.GetTreeById(id);
            var mainElement = _manager.GetParentElement(id);

            var model = new TreeEditView()
            {
                Id = tree.Id,
                Name = tree.Name,
                
                Value = mainElement == null ? String.Empty : mainElement.Value,
                CurrentId = mainElement == null ? String.Empty : mainElement.Id.ToString(),
                SvgObjects = _manager.GetSvgObjects(String.Empty).Select(o => new SvgObjectView()
                {
                    Id = o.Id,
                    Name = o.Name
                })
            };

            return View(model);
        }

        [Authorize(Roles = "Administrator, User")]
        public ActionResult Delete(Guid id)
        {
            var deleted = _manager.DeleteTree(id);
            return deleted ? Content(id.ToString()) : Content(String.Empty);
        }

        public ActionResult Thumbnail(Guid id)
        {
            var thumbnail = _manager.GetThumbnailById(id);
            if (thumbnail == null)
                return File("/Content/no-image.png", "image/png");

            return File(thumbnail.Content, "image/jpg");
        }

        public ActionResult GetXMLTextForImage(Guid id)
        {
            var image = _manager.GetSvgObjectById(id);

            return image == null ? Content(String.Empty) : Content(image.Value);
        }

        public ActionResult GetXmlTextForElement(Guid id)
        {
            var element = _manager.GetTreeElementById(id);

            return Json(new { id = element.Id, imageText = element.Value}, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult CreateParentElement(AjaxData obj)
        {
            TreeElement parentElement = new TreeElement()
            {
                Id = Guid.NewGuid(),
                TreeId = obj.treeId,
                IsParent = true,
                Value = obj.imageText
            };
            _manager.AddTreeElement(parentElement);

            XmlDocument xmlDoc = new XmlDocument();
            xmlDoc.LoadXml(obj.imageText);

            var svgDocument = SvgDocument.Open(xmlDoc);
            var bitmap = svgDocument.Draw();

            Image.GetThumbnailImageAbort im = new Image.GetThumbnailImageAbort(ThumbnailCallBack);
            var thumb = bitmap.GetThumbnailImage(250, 200, im, IntPtr.Zero);

            using (MemoryStream stream = new MemoryStream())
            {
                thumb.Save(stream, ImageFormat.Jpeg);
                var thumbnail = new Thumbnail()
                {
                    Id = obj.treeId,
                    Content = stream.ToArray()
                };
                _manager.AddThumbnail(thumbnail);
            }

            return Content(parentElement.Id.ToString());
        }

        [HttpPost]
        public ActionResult SaveChildImage(AjaxData obj)
        {
            SvgObject objFromLibrary = _manager.GetSvgObjectById(obj.imageId);

            TreeElement child = new TreeElement()
            {
                Id = Guid.NewGuid(),
                IsParent = false,
                TreeId = obj.treeId,
                Value = objFromLibrary.Value
            };
            _manager.AddTreeElement(child);

            return Content(child.Id.ToString());
        }

        [HttpPost]
        public ActionResult ChangeCurrentImage(AjaxData obj)
        {
            _manager.UpdateImageTextForElement(obj.imageId, obj.imageText);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult GetImageText(Guid id)
        {
            TreeElement element = _manager.GetTreeElementById(id);
            return Content(element.Value);
        }


        public ActionResult UnbindImage(Guid imageId)
        {
            _manager.DeleteTreeElement(imageId);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        //public ActionResult SaveThumbnailForTree(Guid id)
        //{

        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_manager != null)
                {
                    _manager.Dispose();
                    _manager = null;
                }
            }
            base.Dispose(disposing);
        }
    }
}

svg/Views/Trees/Add.cshtml
@model svgProject.ViewModels.TreeView

@using (Html.BeginForm("Add", "Trees", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Trees", "Index")
</div>

svg/Views/Trees/Edit.cshtml
@model svgProject.ViewModels.TreeEditView

@{
    ViewBag.Title = "Edit tree";
}

<div class="col-md-12">
    <div class="col-md-4">
        <h3>@Model.Name</h3>
        <hr />
        <input type="hidden" value="@Model.Id" id="tree_id" />
        <input type="hidden" value="@Model.CurrentId" id="current_id" />
        @if (Model.Value == String.Empty)
        {
            <div id="form_add">
                <div class="form-group">
                    @Html.Label("main_image", "Choose main image", new { @class = "control-label" })
                    @Html.DropDownListFor(model => model.ObjectId, Model.SvgObjects.Select(o => new SelectListItem()
               {
                   Value = o.Id.ToString(),
                   Text = o.Name
               }), new { @class = "form-control", id = "parent_image" })
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" id="button_add">Choose</button>
                </div>
            </div>
        }

        <div id="form_select">
            <div class="form-group">
                @Html.LabelFor(model => model.ObjectId, new { @class = "control-label" })
                @Html.DropDownListFor(model => model.ObjectId, Model.SvgObjects.Select(o => new SelectListItem()
           {
               Value = o.Id.ToString(),
               Text = o.Name
           }), new { @class = "form-control", id = "image_to_redirect" })
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="button_bind" disabled>Bind</button>
                <button class="btn btn-primary" id="button_unbind" disabled>Unbind</button>
                <button class="btn btn-default" id="button_prev" disabled><span class="glyphicon glyphicon-chevron-left"></span></button>
                <button class="btn btn-default" id="button_next" disabled><span class="glyphicon glyphicon-chevron-right"></span></button>
            </div>
            <div class="form-group">
                <div id="preview"></div>
            </div>
        </div>

    </div>
    <div class="col-md-8" style="text-align:center;" id="image_text">
        @Html.Raw(Model.Value)
    </div>
</div>

@section Scripts
{
    <script>

        var $pressedElement;
        var currentId = $('#current_id').val();
        var historyRoute = [];
        var elementName = '';

        //отрисовываем картинку при выборе родительского элемента
        $('#parent_image').change(getImageText);

        function getImageText() {
            $.ajax({
                method: 'GET',
                url: '@Url.Action("GetXMLTextForImage")' + '/' + $('#parent_image').val(),
                success: function (response) {
                    $('#button_add').removeAttr('disabled');

                    $('#image_text').empty();
                    $('#image_text').append(response);
                },
                error: function (error) {
                    $('#button_add').attr('disabled', 'disabled');
                    console.log(error);
                    alert('Ошибка при попытке получить изображение');
                }
            });
        }

        //привязываем выбранную картинку к выбранному элементу
        $('#button_bind').click(function () {
            $pressedElement.css('opacity', 1);
            var data = { imageId: $('#image_to_redirect').val(), treeId: $('#tree_id').val() };
            setLoadingForButton($('#button_bind'));
            $.ajax({
                method: 'POST',
                url: '@Url.Action("SaveChildImage")',
                data: JSON.stringify(data),
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $pressedElement.attr('data-child-id', response);

                    $.ajax({
                        method: 'POST',
                        url: '@Url.Action("ChangeCurrentImage")',
                        data: JSON.stringify({ imageId: currentId, imageText: $('#image_text').html() }),
                        contentType: "application/json; charset=utf-8",
                        success: function (response) {
                            console.log(response);
                            setSuccessForButton($('#button_bind'));
                            $('#button_next').removeAttr('disabled');
                            $('#button_bind').attr('disabled', 'disabled');
                            $('#button_unbind').removeAttr('disabled');
                            $pressedElement.css('opacity', 0.5);
                        },
                        error: function (error) {
                            console.error(error);
                        }
                    });

                },
                error: function (error) {
                    console.error(error);
                }
            });
        });

        //отвязываем
        $('#button_unbind').click(function () {
            setLoadingForButton($('#button_unbind'));
            $.ajax({
                method: 'GET',
                url: '@Url.Action("UnbindImage")/?imageId=' + $pressedElement.attr('data-child-id'),
                success: function (response) {
                    $('#button_unbind').attr('disabled', 'disabled');
                    $('#button_bind').removeAttr('disabled');
                    $('#button_next').attr('disabled', 'disabled');
                    setSuccessForButton($('#button_unbind'));
                    $pressedElement.removeAttr('data-child-id');
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });

        //сохранение родительского элемента в бд
        $('#button_add').click(function () {
            var data = { imageText: $('#image_text').html(), treeId: $('#tree_id').val() };
            $.ajax({
                method: 'POST',
                url: '@Url.Action("CreateParentElement")' + '/' + $('#tree_id').val(),
                data: JSON.stringify(data),
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $('#form_add').fadeOut('slow');
                    setImageClickable();
                    console.log(response);
                    currentId = response;
                },
                error: function (error) {
                    console.error(error);
                    alert('Ошибка при попытке добавить элемент');
                }
            });
        });

        //переходим к редактированию привязанной картинки
        $('#button_next').click(function () {

            $.ajax({
                method: 'GET',
                url: '@Url.Action("GetImageText")/' + $pressedElement.attr('data-child-id'),
                success: function (response) {
                    $('#image_text').empty();
                    $('#image_text').append(response);

                    historyRoute.push(currentId);
                    $('#button_prev').removeAttr('disabled', 'disabled');
                    $('#button_next').attr('disabled', 'disabled');
                    $('#button_bind').attr('disabled', 'disabled');
                    $('#button_unbind').attr('disabled', 'disabled');


                    currentId = $pressedElement.attr('data-child-id');
                    $pressedElement = null;
                    setImageClickable();
                    removeClickedAttrubite();
                },
                error: function (error) {
                    console.error(error);
                }
            });

        });

        $('#button_prev').click(function () {
            var imageId = historyRoute[historyRoute.length - 1];
            $.ajax({
                method: 'GET',
                url: '@Url.Action("GetImageText")/' + imageId,
                success: function (response) {
                    $('#image_text').empty();
                    $('#image_text').append(response);
                    $('#button_bind').attr('disabled', 'disabled');
                    $('#button_unbind').attr('disabled', 'disabled');

                    historyRoute.pop();
                    currentId = imageId;
                    $pressedElement = null;
                    setImageClickable();
                    removeClickedAttrubite();
                    $('#button_next').attr('disabled', 'disabled');
                    if (historyRoute.length == 0) {
                        $('#button_prev').attr('disabled', 'disabled');
                    }
                },
                error: function (error) {
                    console.error(error);
                }
            });
        });

        $(document).ready(function () {
            if ($('#parent_image').val())
                getImageText();
            else {
                setImageClickable();
            }
            removeClickedAttrubite();
        });

        $('#image_to_redirect').change(function () {
            $.ajax({
                method: 'GET',
                url: '@Url.Action("GetXMLTextForImage")/' + $('#image_to_redirect').val(),
                success: function (response) {
                    $('#preview').empty();
                    $('#preview').append(response);
                },
                error: function (error) {
                    console.error(error);
                }
            });
        })

        function onElementClick() {

            if ($(this).attr('clicked'))
                return;

            //проверяем привязано ли к элементу изображение
            //и в зависимости от этого (де)активируем кнопки
            if ($(this).attr('data-child-id')) {
                $('#button_unbind').removeAttr('disabled');
                $('#button_bind').attr('disabled', 'disabled');
                $('#button_next').removeAttr('disabled');
            }
            else {
                $('#button_unbind').attr('disabled', 'disabled');
                $('#button_bind').removeAttr('disabled');
                $('#button_next').attr('disabled', 'disabled');
            }

            //убираем анимацию элемента
            $(this).unbind('mouseenter mouseleave');
            $(this).attr('clicked', true);

            //включаем анимацию выбранного ранее элемента
            if ($pressedElement) {
                $pressedElement.css('opacity', 1);
                $pressedElement.removeAttr('clicked');
                $pressedElement.bind('mouseenter', setOpacityHalf);
                $pressedElement.bind('mouseleave', setOpacityFull);
            }

            //запоминаем нажатый элемент
            $pressedElement = $(this);
            $pressedElement.css('opacity', 0.5);

        };

        function setOpacityHalf() {
            $(this).css('opacity', 0.5);
        };

        function setOpacityFull() {
            $(this).css('opacity', 1);
        };

        function setImageClickable() {
            $('path, circle, ellipse, line, polygon, polyline, rect').hover(setOpacityHalf, setOpacityFull);
            $('path, circle, ellipse, line, polygon, polyline, rect').click(onElementClick);
        }

        function removeClickedAttrubite() {
            $('path, circle, ellipse, line, polygon, polyline, rect').each(function (i, element) {
                $(element).removeAttr('clicked');
            });
        }

        function setLoadingForButton($element) {
            elementName = $element.text();
            $element.text('');
            $element.append('<span class="glyphicon glyphicon-refresh"></span>');
        }

        function setSuccessForButton($element) {
            $element.empty();
            $element.append('<span class="glyphicon glyphicon-ok"></span>');
            setTimeout(function () {
                $element.empty();
                $element.text(elementName);
                elementName = '';
            }, 2000);

        }

    </script>

}

svg/Views/Trees/Index.cshtml
@model svgProject.ViewModels.TreesListView
@{
}

@using (Html.BeginForm("Index", "Trees", FormMethod.Get))
{
    <div class="row margin-top-25">
        <div class="col-md-11">
            <div class="input-group">
                <input type="text" name="q" id="q" value="@Model.Keyword" class="form-control" />
                <span class="input-group-btn">
                    <a href="@Url.Action("Index", "Trees")" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></a>
                </span>
            </div>
        </div>
        <div class="col-md-1">
            <button class="btn btn-primary btn-block">Search</button>
        </div>
    </div>
}

<div class="row margin-top-25">
    <div class="col-md-1 col-md-offset-11">
        <a href="@Url.Action("Add")" class="btn btn-primary btn-block">Add</a>
    </div>
</div>
<hr />
<div class="row">
    @foreach (var obj in Model.Trees)
    {

        <div class="col-md-3" id="@obj.Id">
            @Html.Partial("_TreeThumbnail", obj)
        </div>

    }
</div>

@section unobtrusive
{
    @Scripts.Render("~/bundles/unobtrusive")
}

@section Scripts
{
    <script>

        function onDeleteCompleted(response) {
            if (response.responseText == '')
                alert('Delete error');
            else {
                $('#' + response.responseText).fadeOut('slow');
            }
        }

    </script>
}

svg/Views/Trees/Review.cshtml
@model svgProject.ViewModels.ReviewTreeView
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <title>@Model.Name</title>
</head>
<body style="padding-top:10px;">
    <input type="hidden" value="@Model.ParentId" id="parent_id" />
    <div class="col-md-12">
        <button class="btn btn-default" id="button_prev" disabled><span class="glyphicon glyphicon-chevron-left"></span></button>
    </div>
    <div id="image_text">
        @Html.Raw(Model.ImageText)
    </div>


    
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script>

        var historyRoute = [];
        var currentId = '';

        $(document).ready(function () {
            changeCursorForClickable();
            currentId = $('#parent_id').val();
        });

        $('#button_prev').click(function () {
            getImageText(historyRoute.pop());
            if (historyRoute.length == 0) {
                $('#button_prev').attr('disabled', 'disabled');
            }
        });

        function changeCursorForClickable() {
            $('path, circle, ellipse, line, polygon, polyline, rect').each(function (i, elem) {
                if ($(elem).attr('data-child-id')) {
                    $(elem).hover(setCursorPointer, setCursorDefault);
                    $(elem).click(function () {
                        var id = $(this).attr('data-child-id');
                        
                        if (id) {
                            getImageText(id);
                            historyRoute.push(currentId);
                            $('#button_prev').removeAttr('disabled');
                        }
                    });
                }
            });
        }

        function getImageText(id) {
            $.ajax({
                method: 'GET',
                url: '@Url.Action("GetXMLTextForElement")' + '/' + id,
                success: function (response) {
                    $('#image_text').empty();
                    $('#image_text').append(response.imageText);
                    currentId = response.id;
                    changeCursorForClickable();
                },
                error: function (error) {
                    console.log(error);
                    alert('Ошибка при попытке получить изображение');
                }
            });
        }

        function setCursorPointer() {
            $(this).css('cursor', 'pointer');
        }

        function setCursorDefault() {
            $(this).css('cursor', 'default');
        }

    </script>

</body>
</html>

svg/Views/Trees/_TreeThumbnail.cshtml
@model svgProject.ViewModels.TreeThumbnailView

<div class="thumbnail">
    <img src="@Url.Action("Thumbnail", new { id = Model.Id })" alt="thumbnail" />
    <div class="caption" style="word-break:break-word">
        <h3 style="text-align:center;">@Model.Name</h3>
        <p style="text-align:center;">
            <a class="btn btn-default" href="@Url.Action("Review", new { id = Model.Id })" target="_blank">Review</a>
            <a class="btn btn-default" href="@Url.Action("Edit", new { id = Model.Id })">Edit</a>
            @Ajax.ActionLink("Delete", "Delete", new { id = Model.Id }, new AjaxOptions()
       {
           HttpMethod = "POST",
           OnComplete = "onDeleteCompleted"
       },
           new { @class = "btn btn-default" })
        </p>
    </div>
</div>