svg/Controllers/LibraryController.cs
using svg.Models;
using svg.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Svg;
using System.Xml;
using System.Drawing.Imaging;
using System.Drawing;
using svgProject.ViewModels;
using System.Text;

namespace svg.Controllers
{
    [Authorize(Roles = "Administrator, User")]
    public class LibraryController : Controller
    {
        private SvgManager _manager = new SvgManager();

        public ActionResult Index(string q, int page = 1)
        {
            var objects = _manager.GetSvgObjects(q, page);
            var model = new SvgObjectsListView()
            {
                Objects = objects.Select(o => new SvgObjectView()
                {
                    Id = o.Id,
                    Name = o.Name,
                    Value = o.Value
                }),
                Keyword = q,
                CurrentPage = page,
                PagesCount = _manager.GetObjectsCount(q)
            };

            return View(model);
        }

        public ActionResult Add()
        {
            return View(new SvgObjectView());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(SvgObjectView model, HttpPostedFileBase image)
        {
            if (image == null)
                ModelState.AddModelError("image", "Please, choose some image");

            if(ModelState.IsValid)
            {
                var xmlText = new StreamReader(image.InputStream).ReadToEnd();
                var newObject = new SvgObject()
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name,
                    Value = xmlText
                };
                _manager.AddSvgObject(newObject);

                XmlDocument xmlDoc = new XmlDocument();
                xmlDoc.LoadXml(xmlText);

                var svgDocument = SvgDocument.Open(xmlDoc);
                var bitmap = svgDocument.Draw();

                Image.GetThumbnailImageAbort im = new Image.GetThumbnailImageAbort(ThumbnailCallBack);
                var thumb = bitmap.GetThumbnailImage(250, 200, im, IntPtr.Zero);
                
                using (MemoryStream stream = new MemoryStream())
                {
                    thumb.Save(stream, ImageFormat.Jpeg);
                    var thumbnail = new Thumbnail()
                    {
                        Id = newObject.Id,
                        Content = stream.ToArray()
                    };
                    _manager.AddThumbnail(thumbnail);
                }
                return RedirectToAction("Index");
            }

            return View(model);
        }

        //need for method GetThumbnailImage
        private bool ThumbnailCallBack()
        {
            return false;
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var deleted = _manager.DeleteSvgObject(id);
            return deleted ? Content(id.ToString()) : Content(String.Empty);
        }

        public ActionResult Thumbnail(Guid id)
        {
            var thumbnail = _manager.GetThumbnailById(id);
            if (thumbnail == null)
                return View();

            return File(thumbnail.Content, "image/jpg");
        }

        public ActionResult FullImage(Guid id)
        {
            var obj = _manager.GetSvgObjectById(id);
            if (obj == null)
                return HttpNotFound();

            return View(new SvgObjectFullView(obj.Id, obj.Name));
        }

        public ActionResult GetSvgImage(Guid id)
        {
            var obj = _manager.GetSvgObjectById(id);
            if (obj == null)
                return View();

            return Content(obj.Value, "image/svg+xml");
        }

        protected override void Dispose(bool disposing)
        {
            if(disposing)
            {
                if(_manager != null)
                {
                    _manager.Dispose();
                    _manager = null;
                }
            }
            base.Dispose(disposing);
        }
    }
}

svg/Views/Library/Add.cshtml
@model svg.ViewModels.SvgObjectView

@using (Html.BeginForm("Add", "Library", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("image", "Image", new { @class = "control-label col-md-2" })
            <input type="file" name="image" accept=".svg" class="col-md-10" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Library", "Index")
</div>

svg/Views/Library/FullImage.cshtml
@model svgProject.ViewModels.SvgObjectFullView
@{
    Layout = null;
    ViewBag.Title = Model.Name;
}
<img src="@Url.Action("GetSvgImage", new { id = Model.Id })" alt="@Model.Name" />
    @*@Html.Raw(Model.XmlText)*@

svg/Views/Library/Index.cshtml
@model svg.ViewModels.SvgObjectsListView
@{
    ViewBag.Title = "Svg-Objects";
}

@using (Html.BeginForm("Index", "Library", FormMethod.Get))
{
    
    <div class="row margin-top-25">
        <div class="col-md-11">
            <div class="input-group">
                <input type="text" name="q" id="q" value="@Model.Keyword" class="form-control" />
                <span class="input-group-btn">
                    <a href="@Url.Action("Index", "Library")" class="btn btn-default"><span class="glyphicon glyphicon-remove"></span></a>
                </span>
            </div>
        </div>
        <div class="col-md-1">
            <button class="btn btn-primary btn-block">Search</button>
        </div>
    </div>
}

<div class="row margin-top-25">
    <div class="col-md-1 col-md-offset-11">
        <a href="@Url.Action("Add")" class="btn btn-primary btn-block">Add</a>
    </div>
</div>
<hr />
<div class="row">
    @foreach (var obj in Model.Objects)
    {

        <div class="col-md-3" id="@obj.Id">
            @Html.Partial("_ObjectThumbnail", obj)
        </div>

    }
</div>

<input type="hidden" id="pages_count" value="@Model.PagesCount" />
<input type="hidden" id="current_page" value="@Model.CurrentPage" />
<input type="hidden" id="q" value="@Model.Keyword" />

<div style="text-align:center;">
    <ul class="pagination" id="pagination"></ul>
</div>


@section unobtrusive
{
    @Scripts.Render("~/bundles/unobtrusive")
}



@section Scripts
{
    <script src="~/Scripts/jquery.simplePagination.js"></script>
    <script>

        function onDeleteCompleted(response) {
            if (response.responseText == '')
                alert('Delete error');
            else {
                $('#' + response.responseText).fadeOut('slow');
            }
        }

        $('#pagination').pagination({
            cssStyle: 'pagination',
            pages: $('#pages_count').val(),
            currentPage: $('#current_page').val(),
            prevText: '<span aria-hidden="true">&laquo;</span>',
            nextText: '<span aria-hidden="true">&raquo;</span>',
            onPageClick: function (page) {
                if ($('#q').val() == '')
                    window.location = '@Url.Action("Index")?page=' + page;
                else
                    window.location = '@Url.Action("Index", new { q = Model.Keyword })&page=' + page;
            }
        });

    </script>
}

svg/Views/Library/_ObjectThumbnail.cshtml
@model svg.ViewModels.SvgObjectView

<div class="thumbnail">
    @*<img src="@Url.Action("Thumbnail", new { id = Model.Id })" alt="thumbnail" />*@
    <div style="width: 100px; height:100px;">@Html.Raw(Model.Value)</div>
    <div class="caption" style="word-break:break-word">
        <h3 style="text-align:center;">@Model.Name</h3>
        <p style="text-align:center;">
            <a class="btn btn-default" href="@Url.Action("FullImage", new { id = Model.Id })" target="_blank">Full Image</a>
            @*<a class="btn btn-default" href="@Url.Action("Delete", new { id = Model.Id })">Delete</a>*@
            @Ajax.ActionLink("Delete", "Delete", new { id = Model.Id }, new AjaxOptions()
       {
           HttpMethod = "POST",
           OnComplete = "onDeleteCompleted"
       },
           new { @class = "btn btn-default" })
        </p>
    </div>
</div>